apiVersion: v2
name: task-manager
description: A Node.js Task Manager app deployed on AKS
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nodejs
  - task-manager
  - aks
maintainers:
  - name: devops-team
    email: devops@example.com
